import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import Header from "@/components/shared/Header";
>>>>>>> 5a17f9262e4aea0c4336617aa3ee644691db08ce

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "warm-welcome",
=======
  title: "Create Next App",
>>>>>>> 5a17f9262e4aea0c4336617aa3ee644691db08ce
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
      
=======
        {/* Container wrapper */}
>>>>>>> 5a17f9262e4aea0c4336617aa3ee644691db08ce
        <div className=" relative">
          
          {children}
        </div>
      </body>
    </html>
  );
}
